---
retryable_errors:
  - "(?s).*Failed to load state.*tcp.*timeout.*"
  - "(?s).*Failed to load backend.*TLS handshake timeout.*"
  - "(?s).*Creating metric alarm failed.*request to update this alarm is in progress.*"
  - "(?s).*Error installing provider.*TLS handshake timeout.*"
  - "(?s).*Error configuring the backend.*TLS handshake timeout.*"
  - "(?s).*Error installing provider.*tcp.*timeout.*"
  - "(?s).*Failed to query available provider packages.*"
  - "NoSuchBucket: The specified bucket does not exist"
  - "(?s).*Error creating SSM parameter: TooManyUpdates:.*"
  - "(?s).*app.terraform.io.*: 429 Too Many Requests.*"
  - "(?s).*ssh_exchange_identification.*Connection closed by remote host.*"
  - "NoSuchEntity: The user with name .* cannot be found"
  - "(?s).*Error accessing remote module registry.*"
  - "(?s).*connection reset by peer.*"
  - "(?s).*Required plugins are not installed.*"
