---
domain:
  name: "Legacy"
  cidr: 10.56.0.0/14

  env_types:
    prod:
      name: "Prod"
      bootstrap_role_arn: "arn:aws:iam::818996311661:role/BootstrapRole"
      cidr: 10.56.0.0/16
      vendors:
        new_relic:
          account_id: 3274939
          faceless_user_id: 1000488910
          devops_alert_channel_ids: ["6026091", "6026092"]

      regions:
        us-west-1:
          name: us-west-1
          networking:
            cidr: 10.56.0.0/19
            azs:
              us-west-1b:
                cidr: 10.56.0.0/21
              us-west-1c:
                cidr: 10.56.8.0/21
        us-west-2:

    # stage:
    #   name: "Stage"
    #   bootstrap_role_arn: "arn:aws:iam::<ACCOUNT_ID_HERE>:role/BootstrapRole"
    #   cidr: 10.57.0.0/16
    #   vendors:
    #     new_relic:
    #       account_id: 3267165
    #       faceless_user_id: 1000488910
    #       devops_alert_channel_ids: []

    #   regions:
    #     us-west-1:
    #       name: us-west-1
    #       networking:
    #         cidr: 10.57.0.0/19
    #         azs:
    #           us-west-PLACEHOLDER:
    #             cidr: 10.57.0.0/21
    #           us-west-PLACEHOLDER:
    #             cidr: 10.57.8.0/21
    #     us-west-2:

    dev:
      name: "Dev"
      bootstrap_role_arn: "arn:aws:iam::309244295371:role/BootstrapRole"
      cidr: 10.58.0.0/15

      vendors:
        new_relic:
          account_id: 3267164
          faceless_user_id: 1000488910
          devops_alert_channel_ids: ["6026094", "6026096"]

      regions:
        us-west-1:
          name: us-west-1
          networking:
            cidr: 10.58.0.0/18
            azs:
              us-west-1a:
                cidr: 10.58.0.0/20
              us-west-1b:
                cidr: 10.58.16.0/20
        us-west-2:
