---
# the keys here must match the folder names in 300-domains and 500-regions
audit:
  aws_account_ids:
    dev: "424875782146"
    prod: "890372336328"
  account_classes:
    - dev
    - prod
  newrelic_account_ids:
    dev: "3320102"
    prod: "3267142"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Audit
  short_name: Audit

career-nav:
  aws_account_ids:
    dev: "498429487732"
    stage: "705475756481"
    prod: "755583591049"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3526014"
    stage: "3526015"
    prod: "3526016"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Career Nav
  short_name: CareerNav

catalog:
  aws_account_ids:
    dev: "868671425977"
    stage: "097869668767"
    prod: "927313027188"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267143"
    stage: "3267144"
    prod: "3267145"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Catalog
  short_name: Catalog

content-gap-tracker:
  aws_account_ids:
    dev: "565384848751"
    stage: "068794058857"
    prod: "250652661574"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3384588"
    stage: "3384589"
    prod: "3384590"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Content Gap Tracker
  short_name: GapTracker

core:
  aws_account_ids:
    dev: "120504568363"
    stage: "677067598403"
    prod: "952012020802"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267146"
    stage: "3267147"
    prod: "3267148"
  starting_region: us-west-1
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Core
  short_name: Core

course-authoring:
  aws_account_ids:
    dev: "270508724719"
    stage: "974867643943"
    prod: "902848139039"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267149"
    stage: "3267150"
    prod: "3267151"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Course Authoring
  short_name: CourseAuth

coursecloud:
  aws_account_ids:
    dev: "482441027836"
    stage: "965241463723"
    prod: "465706561045"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3318236"
    stage: "3318237"
    prod: "3318239"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: CourseCloud
  short_name: CourseCld

data-science:
  aws_account_ids:
    dev: "421975288677"
    stage: "631152024383"
    prod: "528248901666"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267152"
    stage: "3267153"
    prod: "3267154"
  starting_region: us-west-1
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Data Science
  short_name: DataSci

delivery:
  aws_account_ids:
    dev: "189666774940"
    stage: "478380425125"
    prod: "516121278201"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267155"
    stage: "3267156"
    prod: "3267157"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Delivery
  short_name: Delivery

dotin:
  aws_account_ids:
    dev: "045601965938"
    stage: "994520135602"
    prod: "447521464733"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3437516"
    stage: "3437517"
    prod: "3437518"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Dotin
  short_name: Dotin

it:
  aws_account_ids:
    dev: "570385632360"
    stage: "353464771731"
    prod: "545454935189"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267160"
    stage: "3267161"
    prod: "3267163"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: IT
  short_name: IT

legacy:
  aws_account_ids:
    dev: "309244295371"
    prod: "818996311661"
  account_classes:
    - dev
    - prod
  newrelic_account_ids:
    dev: "3267164"
    prod: "3274939"
  starting_region: us-west-1
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Legacy
  short_name: Legacy

player:
  aws_account_ids:
    dev: "128803882733"
    stage: "943690727927"
    prod: "356754676807"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3318242"
    stage: "3318244"
    prod: "3318243"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Player
  short_name: Player

reveng:
  aws_account_ids:
    dev: "834722263269"
    stage: "722965316008"
    prod: "645269821934"
  account_classes:
    - dev
    - stage
    - prod
  newrelic_account_ids:
    dev: "3267166"
    stage: "3267167"
    prod: "3267168"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: RevEng
  short_name: RevEng

shared-services:
  aws_account_ids:
    dev: "280602929331"
    prod: "262472150594"
  account_classes:
    - dev
    - prod
  newrelic_account_ids:
    dev: "3320100"
    prod: "3318252"
  starting_region: us-west-2
  secrets_to_forward:
    - devops-team/alerts-config
  full_name: Shared Services
  short_name: SharedSvcs
