---
security_portal_global_account_slug: security-portal-global
security_portal_global_region: us-west-2
security_portal_global_operator_profile: security-portal-global-ops
security_portal_product_domain: Security Portal
product_domain_prefix: ""

org_account_id: 354049935716
security_portal_id: 660735784031

newrelic_global_account_id: 2848815
newrelic_global_user_id: 1000488910

okta_aws_app_id: 0oav8tqfmLR9HgRLc5d6
okta_lacework_app_id: 0oa3v6ee5h9T9vhL55d7
